language: csharp  
solution: EF.DbContextFactory.sln
sudo: required  
dist: trusty 
services:
  - docker
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
mono: none
os:
  - linux
  - osx
osx_image: xcode8.2
addons:
  apt:
    packages:
      - libunwind8
branches:  
  only:
    - master
    - dev
before_install:  
  - chmod +x build.sh
script:  
  - ./build.sh
